### PR TITLE
Add Translations

### PR DESCRIPTION
**Pull request by MattRCole**
# What

This pull request adds translations to web-lexica! These have been initially boot-strapped from the translations of [Lexica](https://github.com/lexica/lexica).

There is an abstraction layer (not perfect, but it ought to work) between `lexica` and `web-lexica` found in the [`android-and-web-translation-mappings.js`](translations/android-and-web-translation-mappings.js) file.

Soon, there should be a weblate project available for `web-lexica`.

# Why

So much work has gone into making `lexica` accessible in many different languages. The same ought to be true of `web-lexica`, therefore, this pull request boot-straps a sizeable portion of translations using much of the previous work done to translate `lexica`

### CODE REVIEW

**Comment by pserwylo** [comment]
Awesome as always. Want me to add you as an admin to the Lexuca weblateb project? That way we can add a new "component" for the web version. You can see this in some other projects where we have one component for App Metadata (e.g. FDroid descriptions) and one for Android game strings: https://hosted.weblate.org/projects/beat-feet/#components

If so, what is your username there, same as here?

**Comment by pserwylo** [comment]
Whoops, just saw the readme pointing to the web-lexica weblate project. Carry on 😀

**Comment by MattRCole** [comment]
I didn't even think of that! I'd be more than happy to remove the separate project and more the web-lexica translations in as a subcomponent of lexica's project! Having the projects together makes sense to me.

I believe my username mort_jack on weblate. I'm sure that my email is the same.

Aug 7, 2022 3:47:36 PM Peter Serwylo ***@***.***>:

**Comment by pserwylo** [comment]
Cool, found you (username was `MattRCole` - found them by looking at the person managing the web-lexica project).

image

If it is a hassle, don't stress about moving it over, just wanted to offer this in case you thought it was a good idea. Ta.

**Pull request merged**
