### PR TITLE
Add GitHub deploy action

### PR DESCRIPTION
**Pull request by MattRCole**
@pserwylo Let me know if you would like me to use my email for the `user.email` field

### CODE REVIEW

**Comment by pserwylo** [comment]
Happy for any email, feel free to continue using mine. The commits here are not really of any relevance, we wont be storing a history of commits (rather blowing away commits to the `gh-pages` branch each time we build again). The history is stored in the `master` branch so anybody can build old versions if they like.

**Review by pserwylo — APPROVED** [review]
Looks great! Feel free to merge as you see fit.

**Comment by pserwylo** [comment]
Right, so this will work well with `yarn start` running on `http://localhost:3000` with `BrowserRouter`, but to work on GitHub pages where everything is static, we'll probably need either to use `HashRouter` or to manually copy the `index.html` file to `/multiplayer/index.html` and `/options/index.html` (and all future paths which end up in the router).

**Comment by MattRCole** [comment]
Yeah, I never stopped to think that `github.io` was only a static server and that wouldn't work.

This looks like a pretty good fix:

https://github.com/rafgraph/spa-github-pages/blob/gh-pages/index.html#L21-L42

I went ahead and added it before seeing this message

**Comment by MattRCole** [comment]
I also directly pushed it to master. I need to remember that this is now a collaboration and I shouldn't just do that.

**Comment by MattRCole** [comment]
Okay, #5 should resolve this.

**Pull request merged**
